#!/usr/bin/ruby

tomcat_host=ARGV[0]

if(ret = %x[curl http://#{tomcat_host}:8080/stepsovc/test]) =~ /PingPage/
	puts "Tomcat OK"
	exit(0)
else
	puts "'curl http://#{tomcat_host}:8080/stepsovc/test' returned #{ret.strip}"
	exit(2)
end
